export const videos = [
	{
		id: 1,
		link: "Izw-xaVkO0g",
		minutes: "14:50",
		name: "10 Crucial Personal Finance Lessons",
		owner: "Humphrey Yang",
	},
	{
		id: 2,
		link: "Q0uXGQu55GM",
		minutes: "8:05",
		name: "ACCOUNTANT EXPLAINS: Money Habits Keeping You Poor",
		owner: "Nischa",
	},
	{ id: 3, link: "AqZbO8Ojhmw", minutes: "14:14", name: "The Passive Income Scam", owner: "The Plain Bagel" },
	{
		id: 4,
		link: "dN5qHjnd_xk",
		minutes: "15:30",
		name: "HOW DEBT CAN GENERATE INCOME - ROBERT KIYOSAKI",
		owner: "The Rich Dad Channel",
	},
	{
		id: 5,
		link: "ATDYLTnGJV0",
		minutes: "10:38",
		name: "Simple Steps to Financial Freedom",
		owner: "Matt D'Avella",
	},
	{
		id: 6,
		link: "zVcwvCL2C2c",
		minutes: "7:43",
		name: "A Minimalist Approach to Personal Finance",
		owner: "",
	},
	{
		id: 7,
		link: "bMXTGGxrQ3A",
		minutes: "10:16",
		name: "10 personal finance lessons that changed my life",
		owner: "Matt D'Avella",
	},
	{
		id: 8,
		link: "BBAuhqvT_ds",
		minutes: "43:29",
		name: "My honest advice to someone who wants financial freedom",
		owner: "Ali Abdaal",
	},
	{
		id: 9,
		link: "pXIZsMNnXic",
		minutes: "9:14",
		name: "8 Common Money Mistakes of Middle Class",
		owner: "Chinkee Tan",
	},
	{
		id: 10,
		link: "NgT3QUtLDaQ",
		minutes: "12:30",
		name: "Paano Magpatubo Ng Pera Sa Puno - Create Money with Chinkee Tan",
		owner: "Chinkee Tan",
	},
	{
		id: 11,
		link: "rC5acgc8WA4",
		minutes: "22:48",
		name: "Yumaman From Piso",
		owner: "Reymond 'Boss RDR' delos Reyes",
	},
	{
		id: 12,
		link: "DhGFGof_f10",
		minutes: "10:59",
		name: "10 BIGGEST LIES ABOUT BADYETING",
		owner: "Chinkee Tan",
	},
	{
		id: 13,
		link: "YQj47p5MPTk",
		minutes: "12:35",
		name: "How I Created A Life Long Income By Doing These 3 Simple Strategies",
		owner: "Chinkee Tan",
	},
	{
		id: 14,
		link: "U2i6Tq01Tdc",
		minutes: "32:54",
		name: "Kumita Kahit Natutulog sa Nakakayamang Money Making Machine",
		owner: "Chinkee Tan",
	},
	{
		id: 15,
		link: "VlRQ_LfDpg0",
		minutes: "15:11",
		name: "Paano Mag-INVEST Kahit Maliit Ang Sahod?",
		owner: "WEALTHY MIND PINOY",
	},
	{
		id: 16,
		link: "f_VFJpsCdWg",
		minutes: "8:30",
		name: "Financial Goals: The Pinoy-Style In Financial Planning",
		owner: "Chinkee Tan",
	},
	{
		id: 17,
		link: "xliYzRQfmA8",
		minutes: "11:33",
		name: "MGA DAPAT MONG GAWIN Tuwing Sahod Para Yumaman (Payday Routine)",
		owner: "WEALTHY MIND PINOY",
	},
	{
		id: 18,
		link: "R8pJhWSR-kM",
		minutes: "10:13",
		name: "8 Sakripisyo Para Yumaman",
		owner: "Janitorial Writer",
	},
	{
		id: 19,
		link: "gLCOYoFS7sg",
		minutes: "10:34",
		name: "8 Paraan Para MAGKAROON ng RICH MINDSET!",
		owner: "Janitorial Writer",
	},
	{
		id: 20,
		link: "3sMVQ6U4p4E",
		minutes: "5:31",
		name: "Badjao Kita Na 5k Per Day Nakapagpatayo Ng Bahay",
		owner: "Chinkee Tan",
	},
	{
		id: 21,
		link: "VBJhFniSUZA",
		minutes: "6:17",
		name: "Kung Na Afford Mo 21 Pesos Per Meal, Hindi Ka Na Mahirap!",
		owner: "Chinkee Tan",
	},
	{
		id: 22,
		link: "npT5kt23_lE",
		minutes: "15:47",
		name: "5 Investments Na Magpapayaman Sayo : Saan dapat ilagay ang ipon",
		owner: "WEALTHY MIND PINOY",
	},
	{
		id: 23,
		link: "uDlAAe9bo0A",
		minutes: "9:10",
		name: "SECRET TO FINANCIAL ABUNDANCE",
		owner: "Chinkee Tan",
	},
	{
		id: 24,
		link: "487q3oEBeP4",
		minutes: "5:20",
		name: "Credit Card HOLDERS!!! BE WARNED ABOUT THIS! IT'S HAPPENING",
		owner: "Chinkee Tan",
	},
	{
		id: 25,
		link: "VgQFW1ewlM0",
		minutes: "10:53",
		name: "10 Debt Repayment Strategies That Banks Don't Want You to Know!",
		owner: "Chinkee Tan",
	},
	{
		id: 26,
		link: "6cerq4DJpZc",
		minutes: "5:33",
		name: "10 SIGNS YOU ARE MISMANAGING YOUR MONEY",
		owner: "Chinkee Tan",
	},
	{
		id: 27,
		link: "ejsgBvAyz9Y",
		minutes: "13:47",
		name: "6 Tips Sa Tamang Paghawak Ng Pera : Money Advice",
		owner: "WEALTHY MIND PINOY",
	},
	{
		id: 28,
		link: "beJeJFHxnDI",
		minutes: "8:01",
		name: "The Ultimate Guide to Saving Money on a Tight Budget",
		owner: "Chinkee Tan",
	},
	{
		id: 29,
		link: "g7ZPTRqfz_c",
		minutes: "9:17",
		name: "8 Bagay na Dapat Itigil Para Iwas Ubos Pera",
		owner: "Chinkee Tan",
	},
	{
		id: 30,
		link: "dFl6Lq3YBfk",
		minutes: "6:52",
		name: "Bakit Wala Kang Ipon? Baka Isa Sa Mga Sitwasyong Ito Ang Dahilan",
		owner: "Filipino Success",
	},
	{
		id: 31,
		link: "P6SBS2Jv67A",
		minutes: "5:51",
		name: "Iba’t ibang diskarte sa pag-iipon, alamin! | Dapat Alam Mo!",
		owner: "GMA Public Affairs",
	},
	{
		id: 32,
		link: "2Tm35ZBY4U0",
		minutes: "12:15",
		name: "Negosyo Titan : Bilyonaryong Ramon Ang, Secrets Sa Success Ay...",
		owner: "Chinkee Tan",
	},
];
